### ISSUE TITLE
possible to change persistent notifications to regular notifications?

### ISSUE THREAD

**Issue by hvbhome** [custom-components/sensor.authenticated#12]
hi,
thanks for the last update.

creating persistent notifications for each new authentication has certain ramifications on the system, i would like to prevent. Would like to change to regular notifications.

could the line

`            self.hass.components.persistent_notification.create('{}'.format(ip_address + ' (' + geo_country + ', ' + geo_region + ', ' + geo_city + ')'), 'New successful login from')
`
be adapted to

`            self.hass.components.notify.notify('{}'.format(ip_address + ' (' + geo_country + ', ' + geo_region + ', ' + geo_city + ')'), 'New successful login from')`

and have regular notifications?

the user can always add an automation to create pers. notifications for each or certain regular notification if so desired (by creating a dedicated template, i include one here)

```
- alias: 'Forward notify to persistent notifications'
  id: 'Forward notify to persistent notifications'
#  initial_state: 'on'
  trigger:
    platform: event
    event_type: call_service
    event_data:
      domain: notify
      service: notify
  condition:
    condition: state
    entity_id: input_boolean.forward_notify_persistent
    state: 'on'
  action:
    service: persistent_notification.create
    data_template:
      message: >
        {% set message = trigger.event.data.service_data.message %}
        {% if 'invalid authentication' in message or 'login attempt' in message %}
          {{ message }}: http://www.ip-tracker.org/locator/ip-lookup.php?ip={{ message.split('from ')[1] }}
        {% else %}
          {{ message }}
        {% endif %}

```

btw this works also the other way round ;-)

```
- alias: 'Forward persistent notifications'
  id: 'Forward persistent notifications'
#  initial_state: 'on'
  trigger:
    platform: event
    event_type: call_service
    event_data:
      domain: persistent_notification
      service: create
  condition:
    condition: state
    entity_id: input_boolean.notify_notify
    state: 'on'
  action:
    service: notify.notify
    data_template:
      message: >
        {% set message = trigger.event.data.service_data.message %}
        {% if 'invalid authentication' in message or 'login attempt' in message %}
         Forwarded Pers Not: {{ message }}: http://www.ip-tracker.org/locator/ip-lookup.php?ip={{ message.split('from ')[1] }}
        {% else %}
         Forwarded Pers Not: {{ message }}
        {% endif %}
```

**Comment by ludeeus** [comment]
Hi,

Thanks for your sugestion, but this will **not** work if the user has not defined a `notify.notify`
It will give this error:
```
AttributeError: module 'homeassistant.components.notify' has no attribute 'notify'
```

You are better off construction your ovn notify action like you have in your examples and disable the `persistent_notification` with:

```yaml
sensor:
  - platform: authenticated
    enable_notification: 'False'
```
