### ISSUE TITLE
List of excludes

### ISSUE THREAD

**Issue by rbflurry** [custom-components/sensor.authenticated#28]
is this the correct way to list ip addresses to exclude?

```
- platform: authenticated
  exclude: 192.168.47.202, 192.168.47.90
```

**Comment by ludeeus** [comment]
it should be defined like this:
```yaml
- platform: authenticated
  exclude:
    - 192.168.47.202
    - 192.168.47.90
```
